services:
  performance_test_server:
    image: 10.110.146.236:5000/press_test:v1
    container_name: performance_test_server
    volumes:
      - /data5/yaoqiang/robot/report:/report
      - /data5/yaoqiang/robot/ros_press/src/performance_test/press.sh:/opt/ros/rolling/bin/press
    working_dir: /perf_test_ws/src/performance_test  # 设置默认工作目录
    command: bash -c "tail -f /dev/null" 
    # sysctls:
    #   net.core.rmem_max: 26214400
    #   net.core.wmem_max: 26214400
    #   net.core.rmem_default: 20971520
    #   net.core.wmem_default: 20971520
    shm_size: 20g
    # command: bash -c "/perf_test_ws/src/performance_test/press.sh"
  
  performance_test_client:
    image: 10.110.146.236:5000/press_test:v1
    container_name: performance_test_client
    volumes:
      - /data5/yaoqiang/robot/report:/report
      - /data5/yaoqiang/robot/ros_press/src/performance_test/press.sh:/opt/ros/rolling/bin/press
    working_dir: /perf_test_ws/src/performance_test  # 设置默认工作目录
    shm_size: 20g
    # sysctls:
    #   net.core.rmem_max: 26214400
    #   net.core.wmem_max: 26214400
    #   net.core.rmem_default: 20971520
    #   net.core.wmem_default: 20971520
    command: bash -c "tail -f /dev/null"
  
